// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/d9e6d03e769ee7013bee70e4f73c8e59d932d91d/globalize/globalize-0.1.3.d.ts
interface GlobalizeStatic {
    addCultureInfo(cultureName: string, baseCultureName: string, info: any): void;
    findClosestCulture(name: string): any;
    format(value: any, format: string): string;
    format(value: any, format: string, cultureSelector: string): string;
    localize(key: string): string;
    localize(key: string, cultureSelector: string): string;
    parseDate(value: any): Date;
    parseDate(value: any, formats: any): Date;
    parseDate(value: any, formats: any, culture: string): Date;
    parseInt(value: any): number;
    parseInt(value: any, radix: number): number;
    parseInt(value: any, radix: number, cultureSelector: string): number;
    parseFloat(value: any): number;
    parseFloat(value: any, radix: number): number;
    parseFloat(value: any, radix: number, cultureSelector: string): number;
    culture(cultureSelector: string): any;
}

declare var Globalize: GlobalizeStatic;
